### ISSUE TITLE
change setting of graphing app issue

### ISSUE THREAD

**Issue by Fan0-6** [roybens/MEA_Analysis#21]
When using the graphing app on compiled_networks, we specify the location and color of genotypes, but the first time we submitted it won't change, if we resubmit, then the second time, it got changed

first time wrong
![截屏2024-07-30 13 27 28](https://github.com/user-attachments/assets/0cae2dd7-6f8c-41fc-8841-82977790d785)

second time correct
![截屏2024-07-30 13 27 46](https://github.com/user-attachments/assets/fd9cc73c-af20-4e96-802a-c5753f4a61fa)

**Comment by rohanmalige** [comment]
hey i think i fixed this issue i will send a new pull request

**Comment by rohanmalige** [comment]
I'm closing this issue for now
