### ISSUE TITLE
GUI activity scan 

### ISSUE THREAD

**Issue by Fan0-6** [roybens/MEA_Analysis#29]
generate nothing
error showed: 

![image](https://github.com/user-attachments/assets/31eb60a4-5a25-484f-8f78-b7311aba0be6)

**Comment by mandarmp** [comment]
this is due to the "Full Scan" Assay type
soln is to make the program compliant to use Full Scan too.

**Comment by Fan0-6** [comment]
solved. The activity file name needs to be changed.

**Comment by Fan0-6** [comment]
solved. The activity file name needs to be changed.
